#Practica 1 - Probabilidad y Estadistica
## Analisis de la evolucion poblacional mundial
### Actividad 1 - identificacion de la fuente

**CITA**
UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data]. 
**Preguntas**
¿Quién produjo originalmente los datos? 
United Nations, World Population Prospects (2024).
¿Qué organización los procesa para su utilización en Our World in Data? 
Our World in Data (OWID)
¿Qué representa la variable que analizarás?
El cambio de la poblacion a traves del tiempo
¿Cuántas filas y columnas tiene el dataset? 
tiene 5 columnas y muchas filas
¿Qué tipo de datos contiene la variable Year? 
es numero
¿Existen valores faltantes? 
los de Annual population change
¿Cuántas entidades diferentes contiene el dataset?  
256
¿Cuál es el valor de la media? 
1400307.625
¿Cuál es el valor de la mediana? 
1441427.5
¿Cuál es el valor de la desviación estándar? 
201063.851433

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:\\Users\\vdjun\\OneDrive\\Escritorio\\ISSC\\Semestre5\\TopicosBD\\U1_PRUEBA\\data\\raw\\annual-population-growth\\annual-population-growth.csv')
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [3]:
df.tail()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
38395,Zimbabwe,ZWE,2096,NaN,100752.0
38396,Zimbabwe,ZWE,2097,NaN,91796.0
38397,Zimbabwe,ZWE,2098,NaN,87605.0
38398,Zimbabwe,ZWE,2099,NaN,76670.0
38399,Zimbabwe,ZWE,2100,NaN,70019.0

In [4]:
df.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [5]:
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [6]:
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [7]:
df_extraction_entity = df[["Entity","Year"]]
df_extraction_entity.head(3)

        Entity  Year
0  Afghanistan  1951
1  Afghanistan  1952
2  Afghanistan  1953

In [8]:
df_2020 = df[df["Year"]==2020]
df_2020.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN

In [9]:
df_2020_ext_col1 = df_2020[["Entity","Year"]]
df_2020_ext_col1.head(3)
df_2020_ext_col2 = df[df["Year"]==2020][["Entity","Year"]]
df_2020_ext_col2.head(3)

          Entity  Year
69   Afghanistan  2020
219  Africa (UN)  2020
369      Albania  2020

In [10]:
df_2005_2020 = df[(df["Year"] >= 2005) & (df["Year"] <= 2020) & (df["Entity"]=="Mexico")]
df_2005_2020.shape

(16, 5)

In [11]:
df_2005_2020.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22254,Mexico,MEX,2005,1417373.0,NaN
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN

In [12]:
df_ext_EA = df_2005_2020[["Entity","Annual change in population"]]
df_ext_EA.head(3)

       Entity  Annual change in population
22254  Mexico                    1417373.0
22255  Mexico                    1442162.0
22256  Mexico                    1520690.0

In [13]:
df_2005_2020[["Annual change in population"]].mean()

Annual change in population    1400307.625
dtype: float64

In [14]:
df_2005_2020[["Annual change in population"]].median()

Annual change in population    1441427.5
dtype: float64

In [15]:
df_2005_2020[["Annual change in population"]].var()

Annual change in population    4.042667e+10
dtype: float64

In [16]:
df_2005_2020[["Annual change in population"]].std()

Annual change in population    201063.851433
dtype: float64

In [17]:
df_2005_2020[["Annual change in population"]].min()

Annual change in population    1036075.0
dtype: float64

In [18]:
df_2005_2020[["Annual change in population"]].max()

Annual change in population    1625434.0
dtype: float64

In [19]:
df_ext_EA.mean(numeric_only=True)

Annual change in population    1400307.625
dtype: float64

In [20]:
df["Entity"].nunique()

256

In [21]:
df_1983_2021 = df[(df["Year"] >= 1983) & (df["Year"] <= 2021) & (df["Entity"]=="Luxembourg")]
df_1983_2021.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
20282,Luxembourg,LUX,1983,434.0,NaN
20283,Luxembourg,LUX,1984,409.0,NaN
20284,Luxembourg,LUX,1985,761.0,NaN

In [22]:
df_1983_2021[["Annual change in population"]].mean()

Annual change in population    7056.794872
dtype: float64

In [23]:
df_1983_2021[["Annual change in population"]].median()

Annual change in population    5751.0
dtype: float64

In [24]:
df_1983_2021[["Annual change in population"]].var()

Annual change in population    1.467604e+07
dtype: float64

In [25]:
df_1983_2021[["Annual change in population"]].std()

Annual change in population    3830.932587
dtype: float64

In [26]:
df_1983_2021[["Annual change in population"]].min()

Annual change in population    409.0
dtype: float64

In [27]:
df_1983_2021[["Annual change in population"]].max()

Annual change in population    13971.0
dtype: float64

In [28]:
import sys 
print("Python:", sys.version) 
print("Pandas:", pd.__version__) 
print("NumPy:", np.__version__)

Python: 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.5
NumPy: 2.5.2

In [29]:
df.loc[:,"Entity"]

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
            ...
38395       Zimbabwe
38396       Zimbabwe
38397       Zimbabwe
38398       Zimbabwe
38399       Zimbabwe
Name: Entity, Length: 38400, dtype: str

In [30]:
df.iloc[600:610, 0:2]

             Entity Code
600  American Samoa  ASM
601  American Samoa  ASM
602  American Samoa  ASM
603  American Samoa  ASM
604  American Samoa  ASM
605  American Samoa  ASM
606  American Samoa  ASM
607  American Samoa  ASM
608  American Samoa  ASM
609  American Samoa  ASM

In [31]:
df.loc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [32]:
df.loc[:,["Entity","Year","Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [33]:
df.iloc[:,[0,1,4]]

            Entity Code  Annual population change (Projected)
0      Afghanistan  AFG                                   NaN
1      Afghanistan  AFG                                   NaN
2      Afghanistan  AFG                                   NaN
3      Afghanistan  AFG                                   NaN
4      Afghanistan  AFG                                   NaN
...            ...  ...                                   ...
38395     Zimbabwe  ZWE                              100752.0
38396     Zimbabwe  ZWE                               91796.0
38397     Zimbabwe  ZWE                               87605.0
38398     Zimbabwe  ZWE                               76670.0
38399     Zimbabwe  ZWE                               70019.0

[38400 rows x 3 columns]

In [34]:
df.loc[10000,["Entity","Year","Annual change in population"]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object